# Generated by Django 5.0 on 2026-07-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Peptide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cas_number', models.CharField(blank=True, max_length=50, verbose_name='Número CAS')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('description', models.TextField(verbose_name='Descripción completa')),
                ('molecular_formula', models.CharField(blank=True, max_length=100, verbose_name='Fórmula molecular')),
                ('molecular_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso molecular (Da)')),
                ('purity', models.CharField(default='>98%', max_length=20, verbose_name='Pureza')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='peptides/', verbose_name='Imagen principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peptides', to='store.category')),
            ],
            options={
                'verbose_name': 'Péptido',
                'verbose_name_plural': 'Péptidos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PeptideVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_mg', models.PositiveIntegerField(verbose_name='Cantidad (mg)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (EUR)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU')),
                ('is_active', models.BooleanField(default=True)),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.peptide')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['size_mg'],
                'unique_together': {('peptide', 'size_mg')},
            },
        ),
    ]
