# Generated by Django 5.0 on 2026-07-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peptidevariant',
            name='fulfillment_level',
            field=models.CharField(choices=[('stock_alto', 'Stock alto (los 5 productos estrella)'), ('stock_minimo', 'Stock mínimo (reposición por lotes)')], default='stock_alto', max_length=20, verbose_name='Nivel de fulfillment'),
        ),
        migrations.AddField(
            model_name='peptidevariant',
            name='reorder_point',
            field=models.PositiveIntegerField(default=5, help_text='Cuando el stock cae a este nivel o por debajo, hay que lanzar el siguiente lote al proveedor.', verbose_name='Punto de pedido'),
        ),
    ]
