# Generated by Django 5.0 on 2026-07-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_peptidevariant_fulfillment_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=150, verbose_name='Laboratorio')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Nº de lote')),
                ('tested_date', models.DateField(blank=True, null=True, verbose_name='Fecha de análisis')),
                ('purity', models.CharField(blank=True, max_length=20, verbose_name='Pureza (HPLC)')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='Archivo (PDF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='store.peptide')),
            ],
            options={
                'verbose_name': 'Certificado de análisis',
                'verbose_name_plural': 'Certificados de análisis',
                'ordering': ['peptide__name', '-tested_date'],
            },
        ),
    ]
