# Generated by Django 5.0 on 2026-07-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_certificados_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre y apellidos')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Empresa / laboratorio')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono / WhatsApp')),
                ('message', models.TextField(verbose_name='Productos y cantidades')),
                ('status', models.CharField(choices=[('new', 'Sin atender'), ('quoted', 'Presupuesto enviado'), ('won', 'Convertida en pedido'), ('lost', 'Descartada')], default='new', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud al por mayor',
                'verbose_name_plural': 'Solicitudes al por mayor',
                'ordering': ['-created_at'],
            },
        ),
    ]
