# Generated by Django 6.0.7 on 2026-07-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bulkenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peptide',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Descripción completa'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Descripción completa'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='short_description_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='short_description_es',
            field=models.CharField(max_length=300, null=True, verbose_name='Descripción corta'),
        ),
    ]
