# Generated by Django 5.0 on 2026-07-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_traducciones_catalogo_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='peptide',
            name='product_format',
            field=models.CharField(choices=[('vial', 'Vial liofilizado (hay que reconstituir)'), ('spray', 'Spray nasal líquido (listo para usar)'), ('solvent', 'Disolvente o auxiliar')], default='vial', max_length=10, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='research_background',
            field=models.TextField(blank=True, help_text='Qué se ha estudiado de esta molécula. Si se deja vacío, la ficha enseña la descripción completa en su lugar. Sin afirmaciones de eficacia, dosis ni uso humano.', verbose_name='Contexto de investigación'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='research_background_en',
            field=models.TextField(blank=True, help_text='Qué se ha estudiado de esta molécula. Si se deja vacío, la ficha enseña la descripción completa en su lugar. Sin afirmaciones de eficacia, dosis ni uso humano.', null=True, verbose_name='Contexto de investigación'),
        ),
        migrations.AddField(
            model_name='peptide',
            name='research_background_es',
            field=models.TextField(blank=True, help_text='Qué se ha estudiado de esta molécula. Si se deja vacío, la ficha enseña la descripción completa en su lugar. Sin afirmaciones de eficacia, dosis ni uso humano.', null=True, verbose_name='Contexto de investigación'),
        ),
    ]
