# Generated by Django 5.0 on 2026-07-23 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_contexto_de_investigacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('name_es', models.CharField(max_length=200, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('short_description_es', models.CharField(max_length=300, null=True, verbose_name='Descripción corta')),
                ('short_description_en', models.CharField(max_length=300, null=True, verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del paquete (EUR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Unidades')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.bundle')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_items', to='store.peptidevariant')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['id'],
                'unique_together': {('bundle', 'variant')},
            },
        ),
    ]
