# Generated by Django 5.0 on 2026-07-02 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pago recibido'), ('processing', 'En preparación'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Transferencia bancaria'), ('mollie', 'Tarjeta (Mollie)'), ('crypto', 'Criptomoneda')], default='bank_transfer', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de pago')),
                ('shipping_first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('shipping_last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('shipping_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('shipping_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('shipping_address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('shipping_country', models.CharField(default='ESP', max_length=3, verbose_name='País')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('research_disclaimer_accepted', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('rgpd_accepted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('variant_size_mg', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.peptidevariant')),
            ],
        ),
    ]
