# Generated by Django 5.0 on 2026-07-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mollie_payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID pago Mollie'),
        ),
    ]
