# Generated by Django 5.0 on 2026-07-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_mollie_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bundle_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Paquete'),
        ),
    ]
